### ISSUE TITLE
Face error in self._prepare_deepspeed(*args)

### ISSUE THREAD

**Issue by LT1st** [GuHuangAI/DDM-Public#5]
The result is as follows:
```
Traceback (most recent call last):
  File "train_vae.py", line 332, in <module>
    main(args)
  File "train_vae.py", line 93, in main
    trainer = Trainer(
  File "train_vae.py", line 184, in __init__
    self.accelerator.prepare(self.model, self.opt_ae, self.opt_disc, self.lr_scheduler_ae,
  File "/home/spai/anaconda3/envs/metap/lib/python3.8/site-packages/accelerate/accelerator.py", line 1209, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/spai/anaconda3/envs/metap/lib/python3.8/site-packages/accelerate/accelerator.py", line 1435, in _prepare_deepspeed
    raise ValueError(
ValueError: When using DeepSpeed `accelerate.prepare()` requires you to pass at least one of training or evaluation dataloaders or alternatively set an integer value in `train_micro_batch_size_per_gpu` in the deepspeed config fileor assign integer value to `AcceleratorState().deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu']`.
```

Do you know what shoud I send to this `_prepare_deepspeed`?

**Comment by GuHuangAI** [comment]
Oh, you should run `accelerate config` to set the configurations. Like this:
![32238a5fe5e7ef0d25c1f5bdab93e9d](https://github.com/GuHuangAI/DDM-Public/assets/55237825/8542205d-eccd-4354-b2e7-4fa6e292a6a6)
Do not use DeepSpeed.

**Comment by LT1st** [comment]
Thank you for your advice! It's really nice of you~
